### ISSUE TITLE
How to provide multiple images to condition the video generation?

### ISSUE THREAD

**Issue by Fritskee** [merlresearch/TI2V-Zero#1]
Hello,

Thank you for this very interesting work. 

On your project page, you give the following example:
![make-up](https://github.com/user-attachments/assets/226c2912-56b0-43aa-85d1-8819ced1e7f0)

However, when I look at the `demo_img2vid.py` or the `gen_video_ufc.py` code, I cannot seem to find where we can provide multiple frames as input to the model for the "video prediction" task.

Could you help me with this?

Kind regards,
Frits

**Comment by Fritskee** [comment]
@Nithin-GK any pointers?

**Comment by seohyun8825** [comment]
Have you figured it out? I'm also looking for multiple images conditioning

> @Nithin-GK any pointers?

**Comment by IsmailQayyum** [comment]
Traceback (most recent call last):
  File "C:\Users\Ismail Qayyum\Desktop\FYPMODELS\TI2V-Zero\demo_img2vid.py", line 79, in <module>
    t2v_pipeline = TextToVideoSynthesisPipeline(**config)
  File "C:\Users\Ismail Qayyum\Desktop\FYPMODELS\TI2V-Zero\modelscope_t2v_pipeline.py", line 50, in __init__
    self.model = TextToVideoSynthesis(**args)
  File "C:\Users\Ismail Qayyum\Desktop\FYPMODELS\TI2V-Zero\modelscope_t2v.py", line 108, in __init__
    self.unet.load_state_dict(torch.load(
AttributeError: 'TextToVideoSynthesis' object has no attribute 'unet'
(ti2v) PS C:\Users\Ismail Qayyum\Desktop\FYPMODELS\TI2V-Zero> 



i'm kinda stuck on this error while running demo_img2vid.py, can someone guide me through

**Comment by nihaomiao** [comment]
Hi @Fritskee @seohyun8825, sorry for the late reply! I am busy finding a job this year. This is a research work collaborated with the company so it is hard for us to include all the details. To enable multiple image conditions, you need to change the code "diffusion.py" and "demo_img2vid.py". Here I show some guidelines:

This code is designed for one image condition. And the pretrained model is to generate a 16-frame video. So we repeat the given image 15 times and use the pretrained model to infill the last frame. As mentioned in our paper, the temporal attention mechanism will only use the information from the given images since the other 15 frames are from the given image.

Similarly, to enable multiple image conditions, we also need to repeat some of the given images, and make sure that in each inference, the pretrained model only needs to infill a frame, and the other 15 frames are given. Note that the positions of these frames are not important. 

For instance, in the "given 8 images" example you mentioned, we can repeat the last frame 7 times, so we have 15 given images and let the model predict the 16th one. And this output will be used as the 9th frame. You can also repeat the first frame 7 times. The key is to ensure the model only needs to infill one frame.
